---
- name: install sudo
  pacman: name=sudo state=present

- name: install reflector
  pacman: name=foo state=present update_cache=yes

- name: generate pacman mirrorlist
  command: /usr/bin/reflector --country "United States" -l 200 -p http --sort rate --save /etc/pacman.d/mirrorlist

- name: update pacman package lists
  pacman: update_cache=yes

- name: create normal_user
  user: name={{ normal_user }} createhome=yes group=users groups=wheel

- name: install utilities
  pacman: name={{ item }} state=present
  with_items:
    - curl
    - aria2c
    - rsync
    - openssh
    - ntp
    - alsa-utils

- name: ensure network time is enabled
  service: name=ntpd state=started enabled=yes

- name: install fonts
  pacman: name={{ item }} state=present
  with_items:
    - ttf-dejavu
    - ttf-liberation
    - ttf-droid
    - ttf-inconsolata
    - adobe-source-code-pro-fonts

- name: install GUI
  pacman: name={{ item }} state=present
  with_items:
    - i3-wm
    - i3lock
    - i3status
    - dmenu
    - lightdm
    - lightdm-gtk3-greeter
    - lxappearance
    - arandr
    - elementary-icon-theme
    - xcursor-simpleandsoft

- name: enable GUI on boot
  service: name=lightdm enabled=yes

- name: template i3 configuration
  sudo: yes
  sudo_user: "{{ normal_user }}"
  template: src=i3/config dest=/home/{{ normal_user }}/.i3/config

- name: template i3status configuration
  sudo: yes
  sudo_user: "{{ normal_user }}"
  template: src=i3/i3status dest=/home/{{ normal_user }}/.i3/i3status

- name: template .bashrc
  sudo: yes
  sudo_user: "{{ normal_user }}"
  template: src=bashrc dest=/home/{{ normal_user}}/.bashrc

- name: template Xresources
  sudo: yes
  sudo_user: "{{ normal_user }}"
  template: src=Xresources dest=/home/{{ normal_user }}/.Xresources

- name: install applications
  pacman: name={{ item }} state=present
  with_items:
    - xterm
    - pcmanfm
    - chromium
    - evince
    - gimp
    - viewnior
    - libreoffice
    - vlc
    - texlive-most

