---
- name: install development enviornment
  sudo: yes
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    # C/C++
    - base-devel
    - cmake
    - premake
    # Python
    - python
    - python-pip
    # Ruby
    - ruby
    # Java
    - jdk7-openjdk
    - jdk8-openjdk
    - apache-ant
    - maven
    # Version Control
    - git
    - subversion
    # Editors
    - vim
    # Other tools
    - openssh
    - virtualbox
    - vagrant

- name: configure git name
  command: "/usr/bin/git config --global user.name \"{{ user_real_name }}\""

- name: configure git email
  command: "/usr/bin/git config --global user.email \"{{ user_email }}\""

- name: install jekyll
  gem: name=jekyll state=present

# Vim
- name: create .vimrc directory
  file: path="/home/{{ normal_user }}/.vim/bundle owner={{ normal_user }} group=users state=directory"

- name: install Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest="/home/{{ normal_user }}/.vim/Vundle.vim accept_hostkey=yes"

- name: template .vimrc
  template: src=.vimrc dest=/home/{{ normal_user }}/.vimrc

- name: install Vundle plugins
  command: /usr/bin/vim +VundleInstall +qa!

- name: install YouCompleteMe
  command: "/home/{{ normal_user }}/.vim/bundle/YouCompleteMe/install.sh --clang-completer"
