---
- name: ensure operating system is supported 
  assert: that="ansible_os_family == 'RedHat'"
  
- name: install dependencies
  yum: name={{ item }}
  with_items:
    - java-1.7.0-openjdk
    - maven
  sudo: yes

- name: install Jenkins LTS repository
  get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
  sudo: yes

- name: enable Jenkins LTS repository
  ini_file: dest=/etc/yum.repos.d/jenkins.repo section=jenkins option=enabled value=1
  sudo: yes

- name: trust Jenkins LTS repository key
  rpm_key: key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  sudo: yes

- name: install or update jenkins
  yum: name=jenkins state=latest
  sudo: yes
  notify: restart jenkins
  
- name: ensure jenkins is enabled
  service: name=jenkins state=started enabled=yes
  sudo: yes

- name: open firewall ports
  firewalld: port={{ item }} permanent=true state=enabled
  with_items:
    - 8080/tcp # web ui
    - 8009/tcp # AJP13
  sudo: yes
  notify:
    - reload firewall
