---
- name: Check if operating system is supported
  assert: that="ansible_os_family == 'Debian'"

- name: install murmur
  apt: name=mumble-server
  sudo: yes

- name: template murmur.ini
  template: src=murmur.ini dest=/etc/murmur.ini
  sudo: yes

- name: set superuser password
  command: murmurd -supw {{ murmur_superuser_password }}
  sudo: yes

- name: Ensure murmur is enabled
  service: name=mumble-server state=started enabled=true
  sudo: yes
